discord:
  token: ${DISCORD_TOKEN}

wolvesville:
  token: ${WOV_TOKEN}
  clanId: ${WOV_CLAN}

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  pass: ${DB_PASS}
  db: ${DB_DATABASE}
